# Generated by Django 3.1.4 on 2021-01-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_way'),
    ]

    operations = [
        migrations.AddField(
            model_name='way',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='way',
            name='gain',
            field=models.IntegerField(default=0),
        ),
    ]
